image: reactnativecommunity/react-native-android

definitions:
  caches:
    yarn: /usr/local/share/.cache/yarn
  steps:
    - step: &Lint
        name: "Lint"
        caches:
          - node
          - yarn
        script:
          - echo "Your linting goes here..."
    - step: &Tag
        name: "Tagging commit"
        caches:
          - node
          - yarn
        script:
          - echo "Your deployment to production script goes here..."
          - apt-get update
          - apt-get -y install jq
          - yarn config set version-sign-git-tag false
          - yarn config set version-git-tag false
          - yarn config set version-commit-hooks false
          - export OLD_VERSION=$(jq -r ".version" package.json)
          - yarn version --prepatch --preid alpha
          - git add *
          - export NEW_VERSION=$(jq -r ".version" package.json)
          - export TAG="stg-$NEW_VERSION"
          - echo "New tag $TAG"
          - git add *
          - git commit -m "Update version from $OLD_VERSION to $NEW_VERSION"
          - git tag $TAG
          - git pull --rebase origin $BITBUCKET_BRANCH
          - git push origin $BITBUCKET_BRANCH
          - git push --tags
    - step: &Build
        name: "Build"
        caches:
          - node
          - yarn
        script:
          - echo "Your build goes here..."
pipelines:
  pull-requests:
    "**":
      - step:
          <<: *Lint
  branches:
    main:
      - parallel:
          - step:
              <<: *Lint
          - step:
              <<: *Tag
      - step:
          <<: *Build
          name: Deploy to Staging
          deployment: staging
          trigger: manual
